# Generated by Django 3.1.5 on 2021-11-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название департамент')),
                ('boss_id', models.IntegerField(verbose_name='Директор департамента')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=20, verbose_name='Фамилия сотрудника')),
                ('first_name', models.CharField(max_length=20, verbose_name='Имя сотрудника')),
                ('second_name', models.CharField(blank=True, max_length=20, verbose_name='Отчество сотрудника')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото')),
                ('post', models.IntegerField(verbose_name='Должность')),
                ('salary', models.IntegerField(verbose_name='Оклад')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('department', models.IntegerField(verbose_name='Департамент')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название должности')),
            ],
        ),
    ]
