# Generated by Django 3.1.5 on 2021-11-01 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20211101_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='department',
            new_name='department_id',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='post',
            new_name='post_id',
        ),
    ]
