# Generated by Django 3.1.5 on 2021-11-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20211101_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department_id',
        ),
        migrations.AddField(
            model_name='employee',
            name='department_id',
            field=models.ManyToManyField(related_name='employees', to='employee.Departments', verbose_name='Департамент'),
        ),
        migrations.RemoveField(
            model_name='employee',
            name='post_id',
        ),
        migrations.AddField(
            model_name='employee',
            name='post_id',
            field=models.ManyToManyField(to='employee.Posts', verbose_name='Должность'),
        ),
    ]
